pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'localhost:5000'  // Local registry
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/r-ramos2/cicd-example.git'  // URL for your GitHub repository
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image locally
                    dockerImage = docker.build("user-service:latest")
                }
            }
        }

        stage('Push to Local Registry') {
            steps {
                script {
                    // Optional: Push image to your local registry (if using one)
                    sh 'docker tag user-service:latest $DOCKER_REGISTRY/user-service:latest'
                    sh 'docker push $DOCKER_REGISTRY/user-service:latest'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Update Kubernetes deployment manifest to use local registry image
                    // For local registry
                    sh 'kubectl set image deployment/user-service user-service=$DOCKER_REGISTRY/user-service:latest'
                    
                    // Apply Kubernetes manifests for deployment
                    sh 'kubectl apply -f kubernetes/deployment.yaml'
                    sh 'kubectl apply -f kubernetes/service.yaml'
                }
            }
        }
    }
}
